[package]
name = "tracemoers"
version = "0.1.0"
authors = ["DragSama <49992845+DragSama@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.10"
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0.60"
